### ISSUE TITLE
Error after install the module

### ISSUE THREAD

**Issue by santomegonzalo** [d-a-n/react-native-webbrowser#1]
Hello, I love your module but when i tried to installed it on mac project i'm getting this error 

<img width="1094" alt="screen shot 2016-03-12 at 5 00 37 pm" src="https://cloud.githubusercontent.com/assets/2914973/13725615/c1e26ff2-e874-11e5-98a5-92fb481d16ae.png">

Do you have an idea how to solve it? 

this is my package.json

```
"dependencies": {
    "immutable": "^3.7.6",
    "react-native": "^0.21.0"
  }
```

**Comment by d-a-n** [comment]
@gsantome Please try to delete node_modules/react-native-webbrowser/node_modules/react-native

e.g.
`rm -rf node_modules/react-native-webbrowser/node_modules/react-native`

**Comment by santomegonzalo** [comment]
wow that was fast... now works perfect... thanks for your help!!!

**Comment by egold** [comment]
@d-a-n -- won't this continue to be a problem going forward? should you add the react-native folder in your project to the ignore rules or something?

**Comment by gorjanz** [comment]
I deleted the mention module, and it still doesn't work. Now it fails on each next place, when some other part of the code, depends on something from React-Native. (my case is Portal.js from rn/Libraries)

**Comment by smitthakkar1** [comment]
same here. any update on this ? Or any other alternative ?
